version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:123@dev-db:5432/tarjama
    depends_on:
      - dev-db
    networks:
      - local

  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tarjama
    networks:
      - local

networks:
  local:
    driver: bridge
